apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  labels:
    app: spring-boot-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
      annotations:                    # ← Add this section
        prometheus.io/scrape: "true"   # Prometheus will scrape this pod
        prometheus.io/port: "8080"     # Port your app exposes metrics
        prometheus.io/path: "/actuator/prometheus"  # Metrics endpoint
    spec:
      containers:
      - name: spring-boot-app
        image: nirmaldocker1987/argocdproject:replaceImageTag
        ports:
        - containerPort: 8080
